import type { AbilityDefinition } from "../types";

export const ABILITY_DEFINITIONS: AbilityDefinition[] = [
  {
    id: "frontline-repair",
    name: "前線修理",
    rarity: "Common",
    category: "Base",
    description: "本拠地HPを12回復する。",
    implemented: true,
    effect: { type: "healBase", amount: 12 },
  },
  {
    id: "healing-square",
    name: "回復マス",
    rarity: "Common",
    category: "Board Gimmick",
    description: "盤面に回復マスを2つ生成する。",
    implemented: true,
    effect: { type: "terrain", terrainType: "heal", count: 2 },
  },
  {
    id: "small-trap",
    name: "小さな罠",
    rarity: "Common",
    category: "Board Gimmick",
    description: "敵陣寄りに罠マスを2つ生成する。",
    implemented: true,
    effect: { type: "terrain", terrainType: "trap", count: 2 },
  },
  {
    id: "pawn-evolution",
    name: "歩兵進化",
    rarity: "Common",
    category: "Passive",
    description: "自分の歩が敵陣に入ると、ランダムな実装済み特殊コマに進化する。",
    implemented: true,
    effect: { type: "passive", passiveId: "pawnEvolution" },
  },
  {
    id: "summon-circle",
    name: "召喚陣の火花",
    rarity: "Common",
    category: "Board Gimmick",
    description: "自陣寄りに召喚陣を1つ生成する。",
    implemented: true,
    effect: { type: "terrain", terrainType: "summon", count: 1 },
  },
  {
    id: "home-guard",
    name: "留守番隊",
    rarity: "Common",
    category: "Passive",
    description: "自陣にいる味方が守りやすくなる設計枠。",
    implemented: false,
    effect: { type: "passive", passiveId: "homeGuard" },
  },
  {
    id: "turret-upgrade",
    name: "タレット増設",
    rarity: "Rare",
    category: "Summon",
    description: "自分の本拠地付近に自動攻撃タレットを1つ設置する。",
    implemented: true,
    effect: { type: "summon", pieceType: "turret" },
  },
  {
    id: "ninja-contract",
    name: "忍者契約",
    rarity: "Rare",
    category: "Summon",
    description: "自陣に忍者を1体召喚する。",
    implemented: true,
    effect: { type: "summon", pieceType: "ninja" },
  },
  {
    id: "hyper-mecha-fusion",
    name: "ハイパーメカ融合",
    rarity: "Epic",
    category: "Summon",
    description: "自陣の非王将コマ5体を選び、ハイパーメカ一型へ融合させる。各陣営1機まで。",
    implemented: true,
    effect: { type: "startFusion" },
  },
  {
    id: "king-awe",
    name: "王の威圧",
    rarity: "Rare",
    category: "Passive",
    description: "王将の周囲2マス以内の敵コマは移動候補が削られる。",
    implemented: true,
    effect: { type: "passive", passiveId: "kingAwe" },
  },
  {
    id: "iron-defense",
    name: "鉄壁の守り",
    rarity: "Rare",
    category: "Base",
    description: "本拠地HPを20回復する。",
    implemented: true,
    effect: { type: "healBase", amount: 20 },
  },
  {
    id: "warp-pair",
    name: "双子ワープ",
    rarity: "Rare",
    category: "Board Gimmick",
    description: "盤面にワープマスを2つ生成する。",
    implemented: true,
    effect: { type: "terrain", terrainType: "warp", count: 2 },
  },
  {
    id: "cannon-blueprint",
    name: "砲台兵の設計図",
    rarity: "Rare",
    category: "Summon",
    description: "砲台兵を召喚できるようにする拡張枠。",
    implemented: false,
    effect: { type: "drawLogOnly" },
  },
  {
    id: "double-action",
    name: "二回行動",
    rarity: "Epic",
    category: "Temporary Buff",
    description: "このターン、ランダムな自分のコマ1体が追加で1回行動できる。",
    implemented: true,
    effect: { type: "temporaryDoubleAction" },
  },
  {
    id: "cursed-board",
    name: "呪いの盤面",
    rarity: "Epic",
    category: "Board Gimmick",
    description: "盤面に呪いマスを3つ生成する。止まったコマは次ターン行動不能になる。",
    implemented: true,
    effect: { type: "terrain", terrainType: "curse", count: 3 },
  },
  {
    id: "piece-rebellion",
    name: "駒の反乱",
    rarity: "Epic",
    category: "Sabotage",
    description: "敵の低レアコマ1体を一定確率で味方にする。",
    implemented: true,
    effect: { type: "convertEnemyLowRank", chance: 0.45 },
  },
  {
    id: "god-oracle",
    name: "神託",
    rarity: "Epic",
    category: "Passive",
    description: "次に表示される能力カードのレアリティが上がる。",
    implemented: true,
    effect: { type: "oracle" },
  },
  {
    id: "lava-crack",
    name: "溶岩裂き",
    rarity: "Epic",
    category: "Board Gimmick",
    description: "盤面に溶岩マスを3つ生成する。",
    implemented: true,
    effect: { type: "terrain", terrainType: "lava", count: 3 },
  },
  {
    id: "jujutsu-manual",
    name: "呪術師の教本",
    rarity: "Epic",
    category: "Summon",
    description: "呪術師を召喚する拡張枠。",
    implemented: false,
    effect: { type: "drawLogOnly" },
  },
  {
    id: "god-descent",
    name: "神降ろし",
    rarity: "Legendary",
    category: "Summon",
    description: "本拠地HPを25消費し、神を1体召喚する。",
    implemented: true,
    effect: { type: "summon", pieceType: "god", selfBaseDamage: 55 },
  },
  {
    id: "forbidden-summon",
    name: "禁断召喚",
    rarity: "Legendary",
    category: "Summon",
    description: "本拠地HPを18消費し、神を1体召喚する。",
    implemented: true,
    effect: { type: "summon", pieceType: "god", selfBaseDamage: 45 },
  },
  {
    id: "divine-domain",
    name: "神域",
    rarity: "Legendary",
    category: "Board Gimmick",
    description: "盤面に神域を2つ生成する。",
    implemented: true,
    effect: { type: "terrain", terrainType: "divine", count: 2 },
  },
  {
    id: "board-expansion",
    name: "盤面拡張",
    rarity: "Legendary",
    category: "Board Gimmick",
    description: "外周風の特殊マスを複数生成する。",
    implemented: true,
    effect: { type: "terrain", terrainType: "warp", count: 4 },
  },
  {
    id: "base-cannon",
    name: "本拠地砲撃",
    rarity: "Legendary",
    category: "Sabotage",
    description: "相手本拠地に18ダメージを与える。",
    implemented: true,
    effect: { type: "damageEnemyBase", amount: 18 },
  },
  {
    id: "dragon-egg",
    name: "竜卵の契約",
    rarity: "Legendary",
    category: "Summon",
    description: "ドラゴンを召喚する拡張枠。",
    implemented: false,
    effect: { type: "drawLogOnly" },
  },
  {
    id: "blood-pact",
    name: "血盟召喚",
    rarity: "Cursed",
    category: "Summon",
    description: "本拠地HPを12消費し、忍者を召喚する。",
    implemented: true,
    effect: { type: "summon", pieceType: "ninja", selfBaseDamage: 12 },
  },
  {
    id: "iyana-yatsu-arrival",
    name: "いやなやつ来訪",
    rarity: "Cursed",
    category: "Summon",
    description: "いやなやつを1体召喚する。放置すると増殖し、倒されると相手の王将を妨害する。",
    implemented: true,
    effect: { type: "summon", pieceType: "iyanaYatsu" },
  },
  {
    id: "rotten-crown",
    name: "腐冠の一撃",
    rarity: "Cursed",
    category: "Sabotage",
    description: "自分も5ダメージを受け、相手本拠地に14ダメージを与える。",
    implemented: true,
    effect: { type: "damageEnemyBase", amount: 14, selfBaseDamage: 5 },
  },
  {
    id: "cursed-momentum",
    name: "呪速",
    rarity: "Cursed",
    category: "Passive",
    description: "呪いマスを踏んだ後の反撃を強める設計枠。",
    implemented: false,
    effect: { type: "passive", passiveId: "cursedMomentum" },
  },
  {
    id: "bad-mouth-plus",
    name: "罵詈雑言+",
    rarity: "Cursed",
    category: "Sabotage",
    description: "敵のいやなやつをまとめて退散させる。",
    implemented: true,
    effect: { type: "banishIyanaYatsu" },
  },
  {
    id: "trap-bargain",
    name: "罠商人",
    rarity: "Cursed",
    category: "Board Gimmick",
    description: "自陣にも敵陣にも罠マスを生成する。",
    implemented: true,
    effect: { type: "terrain", terrainType: "trap", count: 4 },
  },
  {
    id: "king-tax",
    name: "王税",
    rarity: "Cursed",
    category: "Base",
    description: "自分の本拠地HPを8消費し、次のカード抽選を強化する。",
    implemented: true,
    effect: { type: "oracle" },
  },
];

export const RARITY_ORDER = ["Common", "Rare", "Epic", "Legendary", "Cursed"] as const;

export const RARITY_WEIGHT: Record<string, number> = {
  Common: 1,
  Rare: 2,
  Epic: 3,
  Legendary: 4,
  Cursed: 3,
};
