import type { PieceDefinition, PieceType } from "../types";

export const PIECE_DEFINITIONS: Record<PieceType, PieceDefinition> = {
  king: {
    type: "king",
    name: "王将",
    shortName: "王",
    score: 1000,
    implemented: true,
    movement: "周囲1マス",
    specialAbility: "倒されると敗北する中核コマ。",
    weakness: "移動距離が短く、包囲に弱い。",
    summonCost: "初期配置のみ",
    maxHp: 1,
  },
  rook: {
    type: "rook",
    name: "飛車",
    shortName: "飛",
    score: 9,
    implemented: true,
    movement: "縦横に直線移動",
    specialAbility: "長い射線で重要コマを狙える。",
    weakness: "斜めに逃げる相手を追いにくい。",
    summonCost: "通常コマ",
    maxHp: 1,
  },
  bishop: {
    type: "bishop",
    name: "角行",
    shortName: "角",
    score: 8,
    implemented: true,
    movement: "斜めに直線移動",
    specialAbility: "遠距離から盤面を切る。",
    weakness: "縦横の隣接処理が苦手。",
    summonCost: "通常コマ",
    maxHp: 1,
  },
  gold: {
    type: "gold",
    name: "金将",
    shortName: "金",
    score: 6,
    implemented: true,
    movement: "前、横、後ろ、前斜めに1マス",
    specialAbility: "王を守る近衛。",
    weakness: "後ろ斜めに動けない。",
    summonCost: "通常コマ",
    maxHp: 1,
  },
  silver: {
    type: "silver",
    name: "銀将",
    shortName: "銀",
    score: 5,
    implemented: true,
    movement: "前、前斜め、後ろ斜めに1マス",
    specialAbility: "攻めの斜め展開が得意。",
    weakness: "横と真後ろに動けない。",
    summonCost: "通常コマ",
    maxHp: 1,
  },
  knight: {
    type: "knight",
    name: "桂馬",
    shortName: "桂",
    score: 4,
    implemented: true,
    movement: "前方2マス先の左右",
    specialAbility: "コマを飛び越えられる。",
    weakness: "後退できない。",
    summonCost: "通常コマ",
    maxHp: 1,
  },
  lance: {
    type: "lance",
    name: "香車",
    shortName: "香",
    score: 3,
    implemented: true,
    movement: "前方に直線移動",
    specialAbility: "縦の圧力を作る。",
    weakness: "横移動できない。",
    summonCost: "通常コマ",
    maxHp: 1,
  },
  pawn: {
    type: "pawn",
    name: "歩兵",
    shortName: "歩",
    score: 1,
    implemented: true,
    movement: "前方1マス",
    specialAbility: "歩兵進化の対象。",
    weakness: "単体では火力が低い。",
    summonCost: "通常コマ",
    maxHp: 1,
  },
  turret: {
    type: "turret",
    name: "自動攻撃タレット",
    shortName: "砲",
    score: 7,
    implemented: true,
    movement: "移動不可",
    specialAbility: "ターン終了時、周囲2マスの敵1体を自動攻撃する。",
    weakness: "動けず、射程外から狙われやすい。",
    summonCost: "本拠地付近に召喚",
    maxHp: 2,
  },
  ninja: {
    type: "ninja",
    name: "忍者",
    shortName: "忍",
    score: 7,
    implemented: true,
    movement: "斜め方向に最大2マス",
    specialAbility: "敵陣深くへ入り込みやすく、タレットに狙われにくい。",
    weakness: "縦横に動けない。",
    summonCost: "召喚カード",
    maxHp: 1,
  },
  god: {
    type: "god",
    name: "神",
    shortName: "神",
    score: 14,
    implemented: true,
    movement: "周囲2マス",
    specialAbility: "3ターンに1回、任意の敵コマ1体を消滅させる。",
    weakness: "倒されると味方全体が弱体化する。召喚時に本拠地HPを大きく消費する。",
    summonCost: "本拠地HP25",
    maxHp: 2,
    large: true,
  },
  man: {
    type: "man",
    name: "男",
    shortName: "男",
    score: 5,
    implemented: true,
    movement: "周囲1マス。きみこちゃんの号令で前に出る。",
    specialAbility: "サーティビルディング5Fで出現する圧の強い取り巻き。",
    weakness: "特殊能力はなく、囲まれるとあっさり倒れる。",
    summonCost: "サーティビルディング5Fボス専用",
    maxHp: 1,
  },
  hyperMecha: {
    type: "hyperMecha",
    name: "ハイパーメカ一型",
    shortName: "機",
    score: 18,
    implemented: true,
    movement: "全方向に最大2マス。演算シミュレータで最大4マス。Ⅱ型は2x2を占有する。",
    specialAbility: "3ターンに1回ランダムな専用強化を獲得する融合兵器。累計5撃破でハイパーメカⅡ型へ変身。",
    weakness: "各陣営1機のみ。作成には自陣の非王将コマ5体を失う。",
    summonCost: "融合カードで自陣5コマを融合。各陣営1機まで",
    maxHp: 5,
    large: true,
  },
  cannon: {
    type: "cannon",
    name: "砲台兵",
    shortName: "砲兵",
    score: 8,
    implemented: false,
    movement: "前後左右1マス",
    specialAbility: "直線3マス先まで攻撃できる。移動と攻撃は同じターンにできない。",
    weakness: "斜めから接近されると弱い。",
    summonCost: "Rare以上の召喚カード",
    maxHp: 1,
  },
  jujutsushi: {
    type: "jujutsushi",
    name: "呪術師",
    shortName: "呪",
    score: 8,
    implemented: false,
    movement: "斜め1マス",
    specialAbility: "敵1体を呪う。3回呪われたコマは消滅する。",
    weakness: "直接戦闘能力が低い。",
    summonCost: "呪いマスがある時",
    maxHp: 1,
  },
  slime: {
    type: "slime",
    name: "スライム",
    shortName: "粘",
    score: 4,
    implemented: false,
    movement: "周囲1マス",
    specialAbility: "倒されると2体に分裂する。",
    weakness: "分裂体は1マスずつしか動けない。",
    summonCost: "Common召喚カード",
    maxHp: 1,
  },
  dragon: {
    type: "dragon",
    name: "ドラゴン",
    shortName: "竜",
    score: 16,
    implemented: false,
    movement: "飛車と角を合わせた直線移動",
    specialAbility: "3ターンに1回、前方範囲攻撃を行う。",
    weakness: "大型で召喚コストが高く、罠の影響を受けやすい。",
    summonCost: "Legendary召喚カードと本拠地HP20",
    maxHp: 3,
    large: true,
  },
  bomber: {
    type: "bomber",
    name: "爆弾兵",
    shortName: "爆",
    score: 5,
    implemented: false,
    movement: "前方1マス、横1マス",
    specialAbility: "敵に取られた時、周囲1マスの全コマを巻き込む。",
    weakness: "味方も爆発に巻き込む。",
    summonCost: "CursedまたはRareカード",
    maxHp: 1,
  },
  copyNinja: {
    type: "copyNinja",
    name: "コピー忍者",
    shortName: "写忍",
    score: 8,
    implemented: false,
    movement: "最後に倒された敵コマの移動をコピー",
    specialAbility: "特殊能力はコピーできないが、移動特性を盗める。",
    weakness: "コピー対象が弱いと性能も下がる。",
    summonCost: "忍者が場にいる時",
    maxHp: 1,
  },
  divineVassal: {
    type: "divineVassal",
    name: "神の眷属",
    shortName: "眷",
    score: 7,
    implemented: false,
    movement: "金将と同じ",
    specialAbility: "神の周囲にいると攻撃力が上がる。神が倒されると消滅する。",
    weakness: "神がいないと召喚も維持もできない。",
    summonCost: "味方の神が盤面にいる時",
    maxHp: 1,
  },
  iyanaYatsu: {
    type: "iyanaYatsu",
    name: "いやなやつ",
    shortName: "嫌",
    score: 6,
    implemented: true,
    movement: "周囲2マス",
    specialAbility: "倒されると敵陣に移動し、王将に行動制限をかける。放置で増殖する。",
    weakness: "罵詈雑言系カードで退散する。",
    summonCost: "Cursedカード",
    maxHp: 1,
  },
  chronomancer: {
    type: "chronomancer",
    name: "時詠み",
    shortName: "時",
    score: 9,
    implemented: false,
    movement: "王将と同じ",
    specialAbility: "味方1体のクールダウンを1ターン短縮する。",
    weakness: "自身は低耐久。",
    summonCost: "Epic以上",
    maxHp: 1,
  },
  barrierGuard: {
    type: "barrierGuard",
    name: "結界守",
    shortName: "結",
    score: 7,
    implemented: false,
    movement: "金将と同じ",
    specialAbility: "隣接する味方が最初に受ける破壊を1回防ぐ。",
    weakness: "遠距離攻撃には結界が薄い。",
    summonCost: "本拠地HPが60以下",
    maxHp: 2,
  },
  gatekeeper: {
    type: "gatekeeper",
    name: "門番",
    shortName: "門",
    score: 6,
    implemented: false,
    movement: "縦横1マス",
    specialAbility: "ワープマスを封鎖または再接続する。",
    weakness: "斜めからの攻撃に弱い。",
    summonCost: "ワープマスが2つ以上ある時",
    maxHp: 1,
  },
  medic: {
    type: "medic",
    name: "薬師",
    shortName: "薬",
    score: 6,
    implemented: false,
    movement: "周囲1マス",
    specialAbility: "隣接する味方か本拠地を少量回復する。",
    weakness: "敵を取れない。",
    summonCost: "Common以上",
    maxHp: 1,
  },
  magnetSoldier: {
    type: "magnetSoldier",
    name: "磁力兵",
    shortName: "磁",
    score: 8,
    implemented: false,
    movement: "縦横2マスまで",
    specialAbility: "金属系コマを1マス引き寄せる。",
    weakness: "神域では能力が不安定になる。",
    summonCost: "Rare以上",
    maxHp: 1,
  },
  shadowDouble: {
    type: "shadowDouble",
    name: "影武者",
    shortName: "影",
    score: 7,
    implemented: false,
    movement: "王将と同じ",
    specialAbility: "一度だけ王将への攻撃を肩代わりする。",
    weakness: "本物の王将から離れると消える。",
    summonCost: "王将の隣接マス",
    maxHp: 1,
  },
  bannerCaptain: {
    type: "bannerCaptain",
    name: "旗本",
    shortName: "旗",
    score: 7,
    implemented: false,
    movement: "銀将と同じ",
    specialAbility: "周囲2マスの低レア味方の移動候補を1つ増やす。",
    weakness: "単独では脅威が低い。",
    summonCost: "歩が3体以上残っている時",
    maxHp: 1,
  },
  engineer: {
    type: "engineer",
    name: "工兵",
    shortName: "工",
    score: 6,
    implemented: false,
    movement: "縦横1マス",
    specialAbility: "罠、回復、召喚陣を1つ作る。",
    weakness: "作ったギミックは敵にも利用される。",
    summonCost: "Board Gimmickカード後",
    maxHp: 1,
  },
  sealPriest: {
    type: "sealPriest",
    name: "封印師",
    shortName: "封",
    score: 9,
    implemented: false,
    movement: "斜め1マス、前1マス",
    specialAbility: "特殊コマ1体の能力を2ターン封じる。",
    weakness: "通常コマには効果が薄い。",
    summonCost: "Epic以上",
    maxHp: 1,
  },
  stormLancer: {
    type: "stormLancer",
    name: "嵐槍兵",
    shortName: "嵐",
    score: 8,
    implemented: false,
    movement: "前方直線3マスまで",
    specialAbility: "移動した経路の隣接敵を後退させる。",
    weakness: "行き止まりに弱い。",
    summonCost: "Rare以上",
    maxHp: 1,
  },
};

export const IMPLEMENTED_SPECIAL_PIECES: PieceType[] = ["turret", "ninja", "god", "man", "iyanaYatsu", "hyperMecha"];
